class Constants:
    FONT = ("Helvetica", 30)
    ERROR_LABEL_MSG = "Error"
    ERROR_LABEL_MSG_COLOR = "red"
    PAGE_MAIN = "Главная"
    PAGE_WORKSHOPS = "Цеха"
    PAGE_ORDERS = "Заказы"
    BUTTON_CREATE = "Создать"
    BUTTON_SEARCH = "Найти"
    BUTTON_DELETE = "Удалить"
    BUTTON_BACK = "Назад"
    BUTTON_EXIT = "Выход"
    BUTTON_LOAD_MORE = "Загрузить еще"
    POPUP_WINDOW_NAME_INPUT_INCOMING_DOCUMENT = "Создание документа прихода"
    POPUP_WINDOW_NAME_INPUT_WORKSHOP = "Создание цеха"
